import { IProductListing } from "@/types/interface";

export const allProducts: IProductListing[] = [
  {
    id: 1,
    slug: "mens-cotton-kurta-beige",
    name: "Men's Cotton Kurta - Beige",
    description:
      "Elegant beige cotton kurta perfect for festive and casual occasions.",
    price: 2499,
    discountedPrice: 1999,
    discountPercent: 20,
    category: "kurtas",
    color: ["beige", "white", "maroon", "olive"],
    inStock: true,
    bestSeller: true,
    rating: 4.8,
    reviewCount: 180,
    productDetails: {
      color: "Beige",
      material: "Cotton",
      work: ["Thread Embroidery"],
      materialCare: "Machine wash with cold water.",
      disclaimer:
        "Slight color variation may occur due to photographic lighting.",
    },
    image: "/kurta.jpeg",
    gallery: [
      "/kurta.jpeg",
      "/kurta.jpeg",
      "/kurta.jpeg",
      "/kurta.jpeg",
      "/kurta.jpeg",
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    skuQuantity: 10,
    createdAt: "2025-07-01T11:00:00Z",
    updatedAt: "2025-07-01T11:00:00Z",
  },
  {
    id: 2,
    slug: "mens-navy-blue-jacket",
    name: "Men's Navy Blue Jacket",
    description:
      "Stylish navy blue jacket designed for modern comfort and warmth.",
    price: 4999,
    discountedPrice: 4299,
    discountPercent: 14,
    category: "jackets",
    color: ["navy blue", "black", "olive", "grey"],
    inStock: true,
    rating: 4.7,
    reviewCount: 150,
    productDetails: {
      color: "Navy Blue",
      material: "Polyester",
      work: ["Quilted Finish"],
      materialCare: "Dry clean only.",
      disclaimer: "Actual product color may slightly vary from image shown.",
    },
    image: "/jacket.png",
    gallery: [
      "/jacket.png",
      "/jacket.png",
      "/jacket.png",
      "/jacket.png",
      "/jacket.png",
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    skuQuantity: 6,
    createdAt: "2025-07-02T10:00:00Z",
    updatedAt: "2025-07-02T10:00:00Z",
  },
  {
    id: 3,
    slug: "mens-white-linen-shirt",
    name: "Men's White Linen Shirt",
    description:
      "Lightweight linen shirt offering all-day comfort with a crisp finish.",
    price: 1999,
    discountedPrice: 1699,
    discountPercent: 15,
    category: "shirts",
    color: ["white", "blue", "grey", "black"],
    inStock: true,
    rating: 4.5,
    reviewCount: 95,
    productDetails: {
      color: "White",
      material: "Linen",
      work: ["Plain"],
      materialCare: "Machine wash with like colors.",
      disclaimer: "Iron inside out for best finish.",
    },
    image: "/shirt.png",
    gallery: [
      "/shirt.png",
      "/shirt.png",
      "/shirt.png",
      "/shirt.png",
      "/shirt.png",
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    skuQuantity: 12,
    createdAt: "2025-07-03T09:00:00Z",
    updatedAt: "2025-07-03T09:00:00Z",
  },
  {
    id: 4,
    slug: "mens-grey-wool-blazer",
    name: "Men's Grey Wool Blazer",
    description:
      "Sophisticated grey wool blazer ideal for business and formal events.",
    price: 7499,
    discountedPrice: 6499,
    discountPercent: 13,
    category: "suits-blazers",
    color: ["grey", "black", "navy blue", "charcoal"],
    inStock: true,
    rating: 4.6,
    reviewCount: 120,
    productDetails: {
      color: "Grey",
      material: "Wool",
      work: ["Plain Weave"],
      materialCare: "Dry clean only.",
      disclaimer: "Slight shade variations may appear due to lighting.",
    },
    image: "/blazer.jpeg",
    gallery: [
      "/blazer.jpeg",
      "/blazer.jpeg",
      "/blazer.jpeg",
      "/blazer.jpeg",
      "/blazer.jpeg",
    ],
    sizes: ["36", "38", "40", "42", "44"],
    skuQuantity: 5,
    createdAt: "2025-07-04T08:00:00Z",
    updatedAt: "2025-07-04T08:00:00Z",
  },
  {
    id: 5,
    slug: "mens-black-formal-trouser",
    name: "Men's Black Formal Trouser",
    description: "Tailored black trousers crafted from premium blended fabric.",
    price: 2999,
    discountedPrice: 2499,
    discountPercent: 17,
    category: "trousers",
    color: ["black", "grey", "navy", "brown"],
    inStock: true,
    rating: 4.4,
    reviewCount: 80,
    productDetails: {
      color: "Black",
      material: "Cotton Blend",
      work: ["Solid"],
      materialCare: "Machine wash, do not tumble dry.",
      disclaimer: "Product color may slightly differ from the display image.",
    },
    image: "/trouser.png",
    gallery: [
      "/trouser.png",
      "/trouser.png",
      "/trouser.png",
      "/trouser.png",
      "/trouser.png",
    ],
    sizes: ["30", "32", "34", "36", "38"],
    skuQuantity: 9,
    createdAt: "2025-07-05T10:00:00Z",
    updatedAt: "2025-07-05T10:00:00Z",
  },
  {
    id: 6,
    slug: "mens-blue-slim-fit-suit",
    name: "Men's Blue Slim Fit Suit",
    description:
      "Premium slim-fit blue suit designed for a sharp and elegant look.",
    price: 9999,
    discountedPrice: 8499,
    discountPercent: 15,
    category: "jhodpuri",
    color: ["blue", "black", "grey", "navy"],
    inStock: true,
    rating: 4.9,
    reviewCount: 200,
    productDetails: {
      color: "Blue",
      material: "Poly Wool",
      work: ["Textured Finish"],
      materialCare: "Dry clean only.",
      disclaimer: "Color may vary slightly depending on screen settings.",
    },
    image: "/coat.jpeg",
    gallery: [
      "/coat.jpeg",
      "/coat.jpeg",
      "/coat.jpeg",
      "/coat.jpeg",
      "/coat.jpeg",
    ],
    sizes: ["38", "40", "42", "44", "46"],
    skuQuantity: 7,
    createdAt: "2025-07-06T11:00:00Z",
    updatedAt: "2025-07-06T11:00:00Z",
  },
  {
    id: 7,
    slug: "mens-maroon-festive-kurta",
    name: "Men's Maroon Festive Kurta",
    description: "Rich maroon kurta crafted with intricate embroidery work.",
    price: 3499,
    discountedPrice: 2799,
    discountPercent: 20,
    category: "kurtas",
    color: ["maroon", "gold", "cream", "navy"],
    inStock: true,
    rating: 4.7,
    reviewCount: 140,
    productDetails: {
      color: "Maroon",
      material: "Cotton Silk",
      work: ["Embroidery"],
      materialCare: "Dry clean for first wash, then gentle hand wash.",
      disclaimer: "Slight thread irregularities are part of hand embroidery.",
    },
    image: "/kurta.jpeg",
    gallery: [
      "/kurta.jpeg",
      "/kurta.jpeg",
      "/kurta.jpeg",
      "/kurta.jpeg",
      "/kurta.jpeg",
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    skuQuantity: 8,
    createdAt: "2025-07-07T12:00:00Z",
    updatedAt: "2025-07-07T12:00:00Z",
  },
  {
    id: 8,
    slug: "mens-black-linen-shirt",
    name: "Men's Black Linen Shirt",
    description:
      "Comfortable and breathable black linen shirt for smart casual wear.",
    price: 1799,
    discountedPrice: 1499,
    discountPercent: 17,
    category: "shirts",
    color: ["black", "white", "olive", "navy"],
    inStock: true,
    rating: 4.5,
    reviewCount: 110,
    productDetails: {
      color: "Black",
      material: "Linen",
      work: ["Plain"],
      materialCare: "Machine wash with mild detergent.",
      disclaimer: "Avoid direct sunlight drying to retain color.",
    },
    image: "/shirt.png",
    gallery: [
      "/shirt.png",
      "/shirt.png",
      "/shirt.png",
      "/shirt.png",
      "/shirt.png",
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    skuQuantity: 10,
    createdAt: "2025-07-08T09:00:00Z",
    updatedAt: "2025-07-08T09:00:00Z",
  },
  {
    id: 9,
    slug: "mens-grey-formal-trouser",
    name: "Men's Grey Formal Trouser",
    description:
      "Classic grey formal trousers with a tailored fit and durable fabric.",
    price: 3199,
    discountedPrice: 2799,
    discountPercent: 12,
    category: "trousers",
    color: ["grey", "black", "navy", "beige"],
    inStock: true,
    rating: 4.6,
    reviewCount: 90,
    productDetails: {
      color: "Grey",
      material: "Cotton Blend",
      work: ["Solid"],
      materialCare: "Machine wash gentle cycle.",
      disclaimer: "Actual color may differ slightly under indoor lighting.",
    },
    image: "/trouser.png",
    gallery: [
      "/trouser.png",
      "/trouser.png",
      "/trouser.png",
      "/trouser.png",
      "/trouser.png",
    ],
    sizes: ["30", "32", "34", "36", "38"],
    skuQuantity: 9,
    createdAt: "2025-07-09T11:00:00Z",
    updatedAt: "2025-07-09T11:00:00Z",
  },
  {
    id: 10,
    slug: "mens-black-three-piece-suit",
    name: "Men's Black Three Piece Suit",
    description:
      "Classic three-piece black suit featuring premium tailoring and comfort.",
    price: 11999,
    discountedPrice: 9999,
    discountPercent: 17,
    category: "jhodpuri",
    color: ["black", "navy", "charcoal", "grey"],
    inStock: true,
    rating: 4.9,
    reviewCount: 250,
    productDetails: {
      color: "Black",
      material: "Wool Blend",
      work: ["Solid"],
      materialCare: "Dry clean recommended.",
      disclaimer:
        "The product might appear slightly different under various lighting.",
    },
    image: "/coat.jpeg",
    gallery: ["/coat.jpeg", "/coat.jpeg", "/coat.jpeg", "/coat.jpeg"],
    sizes: ["38", "40", "42", "44", "46"],
    skuQuantity: 6,
    createdAt: "2025-07-10T10:00:00Z",
    updatedAt: "2025-07-10T10:00:00Z",
  },
  {
    id: 11,
    slug: "mens-olive-cotton-kurta",
    name: "Men's Olive Cotton Kurta",
    description: "Soft olive green kurta ideal for everyday ethnic wear.",
    price: 2299,
    discountedPrice: 1899,
    discountPercent: 17,
    category: "kurtas",
    color: ["olive", "beige", "cream", "maroon"],
    inStock: true,
    rating: 4.6,
    reviewCount: 130,
    productDetails: {
      color: "Olive",
      material: "Cotton",
      work: ["Printed Design"],
      materialCare: "Hand wash separately in cold water.",
      disclaimer: "Prints may fade slightly after multiple washes.",
    },
    image: "/kurta.jpeg",
    gallery: ["/kurta.jpeg", "/kurta.jpeg", "/kurta.jpeg", "/kurta.jpeg"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    skuQuantity: 8,
    createdAt: "2025-07-11T10:00:00Z",
    updatedAt: "2025-07-11T10:00:00Z",
  },
  {
    id: 12,
    slug: "mens-brown-leather-jacket",
    name: "Men's Brown Leather Jacket",
    description:
      "Premium brown leather jacket built for durability and urban style.",
    price: 7999,
    discountedPrice: 6999,
    discountPercent: 12,
    category: "jackets",
    color: ["brown", "black", "tan", "olive"],
    inStock: true,
    rating: 4.8,
    reviewCount: 210,
    productDetails: {
      color: "Brown",
      material: "Leather",
      work: ["Embossed Texture"],
      materialCare: "Use leather cleaner only. Avoid moisture.",
      disclaimer: "Leather develops a natural patina over time.",
    },
    image: "/jacket.png",
    gallery: ["/jacket.png", "/jacket.png", "/jacket.png", "/jacket.png"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    skuQuantity: 6,
    createdAt: "2025-07-12T09:00:00Z",
    updatedAt: "2025-07-12T09:00:00Z",
  },
  {
    id: 13,
    slug: "mens-blue-denim-shirt",
    name: "Men's Blue Denim Shirt",
    description:
      "Casual denim shirt that pairs well with jeans or chinos for an all-day look.",
    price: 2399,
    discountedPrice: 1999,
    discountPercent: 17,
    category: "shirts",
    color: ["blue", "light blue", "black", "grey"],
    inStock: true,
    rating: 4.4,
    reviewCount: 90,
    productDetails: {
      color: "Blue",
      material: "Denim",
      work: ["Washed Finish"],
      materialCare: "Machine wash cold with similar colors.",
      disclaimer: "Color may bleed during first wash.",
    },
    image: "/shirt.png",
    gallery: ["/shirt.png", "/shirt.png", "/shirt.png", "/shirt.png"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    skuQuantity: 12,
    createdAt: "2025-07-13T08:00:00Z",
    updatedAt: "2025-07-13T08:00:00Z",
  },
  {
    id: 14,
    slug: "mens-navy-formal-blazer",
    name: "Men's Navy Formal Blazer",
    description:
      "Elegant navy blazer tailored for formal occasions and business wear.",
    price: 7999,
    discountedPrice: 6899,
    discountPercent: 14,
    category: "suits-blazers",
    color: ["navy", "black", "charcoal", "grey"],
    inStock: true,
    rating: 4.7,
    reviewCount: 140,
    productDetails: {
      color: "Navy",
      material: "Poly Wool",
      work: ["Twill Weave"],
      materialCare: "Dry clean only.",
      disclaimer: "Keep in garment bag to avoid wrinkles.",
    },
    image: "/blazer.jpeg",
    gallery: ["/blazer.jpeg", "/coat.jpeg", "/coat.jpeg", "/coat.jpeg"],
    sizes: ["36", "38", "40", "42", "44"],
    skuQuantity: 5,
    createdAt: "2025-07-14T07:00:00Z",
    updatedAt: "2025-07-14T07:00:00Z",
  },
  {
    id: 15,
    slug: "mens-brown-cotton-trouser",
    name: "Men's Brown Cotton Trouser",
    description:
      "Smart brown cotton trousers perfect for office or casual evenings.",
    price: 2699,
    discountedPrice: 2299,
    discountPercent: 15,
    category: "trousers",
    color: ["brown", "beige", "black", "olive"],
    inStock: true,
    rating: 4.5,
    reviewCount: 100,
    productDetails: {
      color: "Brown",
      material: "Cotton Blend",
      work: ["Solid"],
      materialCare: "Machine wash cold, tumble dry low.",
      disclaimer: "Avoid bleaching to maintain color.",
    },
    image: "/trouser.png",
    gallery: ["/trouser.png", "/trouser.png", "/trouser.png", "/trouser.png"],
    sizes: ["30", "32", "34", "36", "38"],
    skuQuantity: 8,
    createdAt: "2025-07-15T09:00:00Z",
    updatedAt: "2025-07-15T09:00:00Z",
  },
  {
    id: 16,
    slug: "mens-grey-three-piece-suit",
    name: "Men's Grey Three Piece Suit",
    description: "Refined grey suit perfect for weddings and formal events.",
    price: 10999,
    discountedPrice: 9299,
    discountPercent: 15,
    category: "jhodpuri",
    color: ["grey", "black", "blue", "navy"],
    inStock: true,
    rating: 4.8,
    reviewCount: 180,
    productDetails: {
      color: "Grey",
      material: "Wool Blend",
      work: ["Textured Finish"],
      materialCare: "Dry clean recommended.",
      disclaimer: "Store on a hanger to maintain shape.",
    },
    image: "/coat.jpeg",
    gallery: ["/coat.jpeg", "/coat.jpeg", "/coat.jpeg", "/coat.jpeg"],
    sizes: ["38", "40", "42", "44", "46"],
    skuQuantity: 7,
    createdAt: "2025-07-16T10:00:00Z",
    updatedAt: "2025-07-16T10:00:00Z",
  },
  {
    id: 17,
    slug: "mens-cream-silk-kurta",
    name: "Men's Cream Silk Kurta",
    description:
      "Premium cream silk kurta with subtle sheen — ideal for festive wear.",
    price: 3999,
    discountedPrice: 3499,
    discountPercent: 12,
    category: "kurtas",
    color: ["cream", "gold", "white", "beige"],
    inStock: true,
    rating: 4.9,
    reviewCount: 220,
    productDetails: {
      color: "Cream",
      material: "Silk Blend",
      work: ["Embroidery"],
      materialCare: "Dry clean only.",
      disclaimer: "Slight shine variation may occur under different lighting.",
    },
    image: "/kurta.jpeg",
    gallery: ["/kurta.jpeg", "/kurta.jpeg", "/kurta.jpeg", "/kurta.jpeg"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    skuQuantity: 6,
    createdAt: "2025-07-17T10:00:00Z",
    updatedAt: "2025-07-17T10:00:00Z",
  },
  {
    id: 18,
    slug: "mens-grey-bomber-jacket",
    name: "Men's Grey Bomber Jacket",
    description:
      "Trendy bomber jacket crafted in lightweight fabric for a sporty look.",
    price: 4599,
    discountedPrice: 3899,
    discountPercent: 15,
    category: "jackets",
    color: ["grey", "black", "olive", "blue"],
    inStock: true,
    rating: 4.5,
    reviewCount: 125,
    productDetails: {
      color: "Grey",
      material: "Nylon",
      work: ["Quilted Finish"],
      materialCare: "Dry clean only.",
      disclaimer: "Zipper style may slightly vary based on stock.",
    },
    image: "/jacket.png",
    gallery: ["/jacket.png", "/jacket.png", "/jacket.png", "/jacket.png"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    skuQuantity: 8,
    createdAt: "2025-07-18T10:00:00Z",
    updatedAt: "2025-07-18T10:00:00Z",
  },
  {
    id: 19,
    slug: "mens-light-blue-shirt",
    name: "Men's Light Blue Shirt",
    description:
      "Classic light blue shirt perfect for formal meetings or casual Fridays.",
    price: 1999,
    discountedPrice: 1599,
    discountPercent: 20,
    category: "shirts",
    color: ["light blue", "white", "navy", "grey"],
    inStock: true,
    rating: 4.6,
    reviewCount: 160,
    productDetails: {
      color: "Light Blue",
      material: "Cotton",
      work: ["Plain"],
      materialCare: "Machine wash warm with like colors.",
      disclaimer: "Slight creases may appear due to packaging.",
    },
    image: "/shirt.png",
    gallery: ["/shirt.png", "/shirt.png", "/shirt.png", "/shirt.png"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    skuQuantity: 10,
    createdAt: "2025-07-19T10:00:00Z",
    updatedAt: "2025-07-19T10:00:00Z",
  },
  {
    id: 20,
    slug: "mens-charcoal-office-blazer",
    name: "Men's Charcoal Office Blazer",
    description:
      "Charcoal blazer designed for corporate and semi-formal occasions.",
    price: 7499,
    discountedPrice: 6799,
    discountPercent: 9,
    category: "suits-blazers",
    color: ["charcoal", "black", "navy", "grey"],
    inStock: true,
    rating: 4.5,
    reviewCount: 115,
    productDetails: {
      color: "Charcoal",
      material: "Wool Blend",
      work: ["Textured Weave"],
      materialCare: "Dry clean only.",
      disclaimer: "Keep folded properly to maintain structure.",
    },
    image: "/coat.jpeg",
    gallery: ["/coat.jpeg", "/coat.jpeg", "/coat.jpeg", "/coat.jpeg"],
    sizes: ["36", "38", "40", "42", "44"],
    skuQuantity: 4,
    createdAt: "2025-07-20T10:00:00Z",
    updatedAt: "2025-07-20T10:00:00Z",
  },
  {
    id: 21,
    slug: "mens-navy-chinos-trouser",
    name: "Men's Navy Chinos Trouser",
    description:
      "Comfortable chinos crafted from stretchable cotton fabric for daily wear.",
    price: 2599,
    discountedPrice: 2199,
    discountPercent: 15,
    category: "trousers",
    color: ["navy", "khaki", "olive", "black"],
    inStock: true,
    rating: 4.4,
    reviewCount: 130,
    productDetails: {
      color: "Navy",
      material: "Cotton Lycra",
      work: ["Solid"],
      materialCare: "Machine wash gentle cycle.",
      disclaimer: "Slight shrinkage possible after first wash.",
    },
    image: "/trouser.png",
    gallery: ["/trouser.png", "/trouser.png", "/trouser.png", "/trouser.png"],
    sizes: ["30", "32", "34", "36", "38"],
    skuQuantity: 8,
    createdAt: "2025-07-21T10:00:00Z",
    updatedAt: "2025-07-21T10:00:00Z",
  },
  {
    id: 22,
    slug: "mens-navy-double-breasted-suit",
    name: "Men's Navy Double Breasted Suit",
    description:
      "Luxury navy double-breasted suit tailored for formal perfection.",
    price: 12999,
    discountedPrice: 10999,
    discountPercent: 15,
    category: "jhodpuri",
    color: ["navy", "black", "blue", "grey"],
    inStock: true,
    rating: 4.9,
    reviewCount: 240,
    productDetails: {
      color: "Navy",
      material: "Wool Blend",
      work: ["Solid"],
      materialCare: "Dry clean only.",
      disclaimer: "Avoid direct sunlight for long durations.",
    },
    image: "/coat.jpeg",
    gallery: ["/coat.jpeg", "/coat.jpeg", "/coat.jpeg", "/coat.jpeg"],
    sizes: ["38", "40", "42", "44", "46"],
    skuQuantity: 6,
    createdAt: "2025-07-22T10:00:00Z",
    updatedAt: "2025-07-22T10:00:00Z",
  },
  {
    id: 23,
    slug: "mens-golden-festive-kurta",
    name: "Men's Golden Festive Kurta",
    description:
      "Shimmering golden kurta designed for grand festive occasions.",
    price: 3799,
    discountedPrice: 3299,
    discountPercent: 13,
    category: "kurtas",
    color: ["gold", "cream", "maroon", "beige"],
    inStock: true,
    rating: 4.8,
    reviewCount: 180,
    productDetails: {
      color: "Gold",
      material: "Silk Blend",
      work: ["Zari Embroidery"],
      materialCare: "Dry clean only.",
      disclaimer: "Zari work may vary slightly in pattern.",
    },
    image: "/kurta.jpeg",
    gallery: ["/kurta.jpeg", "/kurta.jpeg", "/kurta.jpeg", "/kurta.jpeg"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    skuQuantity: 5,
    createdAt: "2025-07-23T10:00:00Z",
    updatedAt: "2025-07-23T10:00:00Z",
  },
  {
    id: 24,
    slug: "mens-black-puffer-jacket",
    name: "Men's Black Puffer Jacket",
    description:
      "Warm and lightweight black puffer jacket ideal for cold weather.",
    price: 5999,
    discountedPrice: 4999,
    discountPercent: 17,
    category: "jackets",
    color: ["black", "grey", "olive", "navy"],
    inStock: true,
    rating: 4.8,
    reviewCount: 220,
    productDetails: {
      color: "Black",
      material: "Polyester",
      work: ["Quilted Finish"],
      materialCare: "Dry clean only.",
      disclaimer: "Keep away from sharp objects to prevent tears.",
    },
    image: "/jacket.png",
    gallery: ["/jacket.png", "/jacket.png", "/jacket.png", "/jacket.png"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    skuQuantity: 7,
    createdAt: "2025-07-24T10:00:00Z",
    updatedAt: "2025-07-24T10:00:00Z",
  },
  {
    id: 25,
    slug: "mens-white-casual-shirt",
    name: "Men's White Casual Shirt",
    description:
      "A crisp white shirt perfect for casual brunches and semi-formal wear.",
    price: 1799,
    discountedPrice: 1499,
    discountPercent: 17,
    category: "shirts",
    color: ["white", "cream", "light blue", "olive"],
    inStock: true,
    rating: 4.6,
    reviewCount: 170,
    productDetails: {
      color: "White",
      material: "Cotton",
      work: ["Plain"],
      materialCare: "Machine wash warm, iron at low heat.",
      disclaimer: "May require starch for crisp finish.",
    },
    image: "/shirt.png",
    gallery: ["/shirt.png", "/shirt.png", "/shirt.png", "/shirt.png"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    skuQuantity: 10,
    createdAt: "2025-07-25T10:00:00Z",
    updatedAt: "2025-07-25T10:00:00Z",
  },
];
