import { IProductListing } from "@/types/interface";

export const allProducts: IProductListing[] = [
  {
    id: 1,
    slug: "classic-navy-blue-suit",
    name: "Classic Navy Blue Suit",
    description: "Tailored-fit formal suit made from premium poly-viscose fabric. Perfect for weddings and business events.",
    price: 4999,
    discountedPrice: 3999,
    discountPercent: 20,
    category: "suits",
    fabricType: "cotton",
    color: ["blue", "light blue"],
    fabric: "cotton",
    inStock: true,
    bestSeller: true,
    rating: 4.6,
    reviewCount: 215,
    image: "/jacket.png",
    gallery: ["/images/products/suit-navy-blue.jpg", "/images/products/suit-navy-blue-back.jpg", "/images/products/suit-navy-blue-closeup.jpg"],
    sizes: ["S", "M", "L", "XL", "XXL", "3XL"],
    skuQuantity: 1,
    createdAt: "2024-12-15T10:30:00Z",
    updatedAt: "2025-10-10T09:00:00Z",
    materialCare: "Dry clean only. Do not bleach.",
  },
  {
    id: 2,
    slug: "slim-fit-white-shirt",
    name: "Slim Fit White Shirt",
    description: "Elegant slim-fit shirt made with breathable cotton for daily office wear.",
    price: 1499,
    discountedPrice: 1299,
    discountPercent: 13,
    category: "suits",
    fabricType: "cotton",
    color: ["white"],
    fabric: "cotton",
    inStock: true,
    bestSeller: false,
    rating: 4.2,
    reviewCount: 120,
    image: "/coat.jpeg",
    gallery: ["/coat.jpeg"],
    sizes: ["S", "M", "L", "XL"],
    skuQuantity: 10,
    createdAt: "2025-01-10T08:00:00Z",
    updatedAt: "2025-10-10T09:00:00Z",
    materialCare: "Machine wash cold. Do not bleach.",
  },
  {
    id: 3,
    slug: "grey-formal-trousers",
    name: "Grey Formal Trousers",
    description: "Comfortable and stylish grey trousers for office and semi-formal events.",
    price: 2499,
    discountedPrice: 1999,
    discountPercent: 20,
    category: "trousers",
    fabricType: "wool",
    color: ["grey"],
    fabric: "wool",
    inStock: false,
    bestSeller: false,
    rating: 4.0,
    reviewCount: 45,
    image: "/trouser.png",
    gallery: ["/images/products/trousers-grey.jpg"],
    sizes: ["M", "L", "XL"],
    skuQuantity: 0,
    createdAt: "2025-02-15T12:00:00Z",
    updatedAt: "2025-10-10T09:00:00Z",
    materialCare: "Dry clean only.",
  },
  {
    id: 4,
    slug: "casual-beige-linen-shirt",
    name: "Casual Beige Linen Shirt",
    description: "Lightweight linen shirt perfect for summer outings.",
    price: 1799,
    discountedPrice: 1499,
    discountPercent: 17,
    category: "shirts",
    fabricType: "linen",
    color: ["beige"],
    fabric: "linen",
    inStock: true,
    bestSeller: true,
    rating: 4.5,
    reviewCount: 85,
    image: "/shirt.png",
    gallery: ["/images/products/shirt-beige.jpg"],
    sizes: ["S", "M", "L"],
    skuQuantity: 5,
    createdAt: "2024-11-05T10:00:00Z",
    updatedAt: "2025-10-10T09:00:00Z",
    materialCare: "Machine wash cold. Iron on low heat.",
  },
  {
    id: 5,
    slug: "black-evening-blazer",
    name: "Black Evening Blazer",
    description: "Perfect for evening events, made from premium wool blend.",
    price: 6999,
    discountedPrice: 5999,
    discountPercent: 14,
    category: "blazers",
    fabricType: "wool",
    color: ["black"],
    fabric: "wool",
    inStock: true,
    bestSeller: false,
    rating: 4.7,
    reviewCount: 300,
    image: "/blazer.jpeg",
    gallery: ["/images/products/blazer-black.jpg"],
    sizes: ["M", "L", "XL", "XXL"],
    skuQuantity: 3,
    createdAt: "2025-03-20T11:00:00Z",
    updatedAt: "2025-10-10T09:00:00Z",
    materialCare: "Dry clean only.",
  },
  {
    id: 6,
    slug: "casual-checkered-shirt",
    name: "Casual Checkered Shirt",
    description: "Trendy checkered shirt for casual outings and office casuals.",
    price: 1299,
    discountedPrice: 1199,
    discountPercent: 8,
    category: "shirts",
    fabricType: "cotton",
    color: ["red", "black"],
    fabric: "cotton",
    inStock: true,
    bestSeller: true,
    rating: 4.3,
    reviewCount: 60,
    image: "/shirt.png",
    gallery: ["/images/products/shirt-checkered.jpg"],
    sizes: ["S", "M", "L", "XL"],
    skuQuantity: 7,
    createdAt: "2025-04-01T09:00:00Z",
    updatedAt: "2025-10-10T09:00:00Z",
    materialCare: "Machine wash cold.",
  },
  {
    id: 7,
    slug: "ethnic-kurta-maroon",
    name: "Ethnic Kurta - Maroon",
    description: "Traditional maroon kurta with intricate embroidery.",
    price: 2399,
    discountedPrice: 1999,
    discountPercent: 17,
    category: "kurtas",
    fabricType: "silk",
    color: ["maroon"],
    fabric: "silk",
    inStock: false,
    bestSeller: true,
    rating: 4.8,
    reviewCount: 90,
    image: "/kurta.jpeg",
    gallery: ["/images/products/kurta-maroon.jpg"],
    sizes: ["M", "L", "XL"],
    skuQuantity: 0,
    createdAt: "2024-12-25T10:00:00Z",
    updatedAt: "2025-10-10T09:00:00Z",
    materialCare: "Dry clean only.",
  },
  {
    id: 8,
    slug: "summer-polo-tee",
    name: "Summer Polo Tee",
    description: "Lightweight cotton polo t-shirt for casual wear.",
    price: 999,
    discountedPrice: 799,
    discountPercent: 20,
    category: "shirts",
    fabricType: "cotton",
    color: ["white", "blue"],
    fabric: "cotton",
    inStock: true,
    bestSeller: false,
    rating: 4.1,
    reviewCount: 30,
    image: "/shirt.png",
    gallery: ["/images/products/polo-white.jpg"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    skuQuantity: 15,
    createdAt: "2025-05-10T08:00:00Z",
    updatedAt: "2025-10-10T09:00:00Z",
    materialCare: "Machine wash cold. Do not bleach.",
  },
  {
    id: 9,
    slug: "mens-wool-sweater",
    name: "Men's Wool Sweater",
    description: "Warm wool sweater for winter, available in multiple colors.",
    price: 2999,
    discountedPrice: 2499,
    discountPercent: 17,
    category: "jackets",
    fabricType: "wool",
    color: ["grey", "black", "navy"],
    fabric: "wool",
    inStock: true,
    bestSeller: true,
    rating: 4.6,
    reviewCount: 110,
    image: "/jacket.png",
    gallery: ["/images/products/sweater-grey.jpg"],
    sizes: ["M", "L", "XL"],
    skuQuantity: 8,
    createdAt: "2025-06-05T10:00:00Z",
    updatedAt: "2025-10-10T09:00:00Z",
    materialCare: "Hand wash recommended.",
  },
  {
    id: 10,
    slug: "mens-black-leather-jacket",
    name: "Men's Black Leather Jacket",
    description: "Premium leather jacket, perfect for winter and casual wear.",
    price: 8999,
    discountedPrice: 7999,
    discountPercent: 11,
    category: "jackets",
    fabricType: "leather",
    color: ["black"],
    fabric: "leather",
    inStock: true,
    bestSeller: true,
    rating: 4.9,
    reviewCount: 210,
    image: "/jacket.png",
    gallery: ["/images/products/jacket-black.jpg"],
    sizes: ["M", "L", "XL", "XXL"],
    skuQuantity: 4,
    createdAt: "2025-07-01T11:00:00Z",
    updatedAt: "2025-07-01T11:00:00Z",
    materialCare: "Use leather cleaner. Avoid water contact.",
  },
];
