import { IProductListing } from "@/types/interface";

export const allProducts: IProductListing[] = [
  {
    id: 1,
    slug: "mens-cotton-kurta-beige",
    name: "Men's Cotton Kurta - Beige",
    description: "Elegant beige cotton kurta perfect for festive and casual occasions.",
    price: 2499,
    discountedPrice: 1999,
    discountPercent: 20,
    category: "kurtas",
    color: ["beige"],
    inStock: true,
    bestSeller: true,
    rating: 4.8,
    reviewCount: 180,
    productDetails: {
      color: "Beige",
      material: "Cotton",
      work: ["Thread Embroidery"],
      materialCare: "Machine wash with cold water.",
      disclaimer: "Slight color variation may occur due to photographic lighting."
    },
    image: "/linen.png",
    gallery: ["/wool.png", "/silk.png", "/linen.png", "/coat.jpeg"],
    sizes: ["M", "L", "XL", "XXL"],
    skuQuantity: 10,
    createdAt: "2025-07-01T11:00:00Z",
    updatedAt: "2025-07-01T11:00:00Z"
  },
  {
    id: 2,
    slug: "mens-navy-blue-jacket",
    name: "Men's Navy Blue Jacket",
    description: "Stylish navy blue jacket designed for modern comfort and warmth.",
    price: 4999,
    discountedPrice: 4299,
    discountPercent: 14,
    category: "jackets",
    color: ["navy blue"],
    inStock: true,
    rating: 4.7,
    reviewCount: 150,
    productDetails: {
      color: "Navy Blue",
      material: "Polyester",
      work: ["Quilted Finish"],
      materialCare: "Dry clean only.",
      disclaimer: "Actual product color may slightly vary from image shown."
    },
    image: "/coat.jpeg",
    gallery: ["/wool.png", "/silk.png", "/linen.png", "/coat.jpeg"],
    sizes: ["M", "L", "XL"],
    skuQuantity: 6,
    createdAt: "2025-07-02T10:00:00Z",
    updatedAt: "2025-07-02T10:00:00Z"
  },
  {
    id: 3,
    slug: "mens-white-linen-shirt",
    name: "Men's White Linen Shirt",
    description: "Lightweight linen shirt offering all-day comfort with a crisp finish.",
    price: 1999,
    discountedPrice: 1699,
    discountPercent: 15,
    category: "shirts",
    color: ["white"],
    inStock: true,
    rating: 4.5,
    reviewCount: 95,
    productDetails: {
      color: "White",
      material: "Linen",
      work: ["Plain"],
      materialCare: "Machine wash with like colors.",
      disclaimer: "Iron inside out for best finish."
    },
    image: "/linen.png",
    gallery: ["/wool.png", "/silk.png", "/linen.png", "/coat.jpeg"],
    sizes: ["M", "L", "XL", "XXL"],
    skuQuantity: 12,
    createdAt: "2025-07-03T09:00:00Z",
    updatedAt: "2025-07-03T09:00:00Z"
  },
  {
    id: 4,
    slug: "mens-grey-wool-blazer",
    name: "Men's Grey Wool Blazer",
    description: "Sophisticated grey wool blazer ideal for business and formal events.",
    price: 7499,
    discountedPrice: 6499,
    discountPercent: 13,
    category: "blazers",
    color: ["grey"],
    inStock: true,
    rating: 4.6,
    reviewCount: 120,
    productDetails: {
      color: "Grey",
      material: "Wool",
      work: ["Plain Weave"],
      materialCare: "Dry clean only.",
      disclaimer: "Slight shade variations may appear due to lighting."
    },
    image: "/wool.png",
    gallery: ["/wool.png", "/silk.png", "/linen.png", "/coat.jpeg"],
    sizes: ["M", "L", "XL"],
    skuQuantity: 5,
    createdAt: "2025-07-04T08:00:00Z",
    updatedAt: "2025-07-04T08:00:00Z"
  },
  {
    id: 5,
    slug: "mens-black-formal-trouser",
    name: "Men's Black Formal Trouser",
    description: "Tailored black trousers crafted from premium blended fabric.",
    price: 2999,
    discountedPrice: 2499,
    discountPercent: 17,
    category: "trousers",
    color: ["black"],
    inStock: true,
    rating: 4.4,
    reviewCount: 80,
    productDetails: {
      color: "Black",
      material: "Cotton Blend",
      work: ["Solid"],
      materialCare: "Machine wash, do not tumble dry.",
      disclaimer: "Product color may slightly differ from the display image."
    },
    image: "/coat.jpeg",
    gallery: ["/wool.png", "/silk.png", "/linen.png", "/coat.jpeg"],
    sizes: ["30", "32", "34", "36"],
    skuQuantity: 9,
    createdAt: "2025-07-05T10:00:00Z",
    updatedAt: "2025-07-05T10:00:00Z"
  },
  {
    id: 6,
    slug: "mens-blue-slim-fit-suit",
    name: "Men's Blue Slim Fit Suit",
    description: "Premium slim-fit blue suit designed for a sharp and elegant look.",
    price: 9999,
    discountedPrice: 8499,
    discountPercent: 15,
    category: "suits",
    color: ["blue"],
    inStock: true,
    rating: 4.9,
    reviewCount: 200,
    productDetails: {
      color: "Blue",
      material: "Poly Wool",
      work: ["Textured Finish"],
      materialCare: "Dry clean only.",
      disclaimer: "Color may vary slightly depending on screen settings."
    },
    image: "/wool.png",
    gallery: ["/wool.png", "/silk.png", "/linen.png", "/coat.jpeg"],
    sizes: ["38", "40", "42", "44"],
    skuQuantity: 7,
    createdAt: "2025-07-06T11:00:00Z",
    updatedAt: "2025-07-06T11:00:00Z"
  },
  {
    id: 7,
    slug: "mens-maroon-festive-kurta",
    name: "Men's Maroon Festive Kurta",
    description: "Rich maroon kurta crafted with intricate embroidery work.",
    price: 3499,
    discountedPrice: 2799,
    discountPercent: 20,
    category: "kurtas",
    color: ["maroon"],
    inStock: true,
    rating: 4.7,
    reviewCount: 140,
    productDetails: {
      color: "Maroon",
      material: "Cotton Silk",
      work: ["Embroidery"],
      materialCare: "Dry clean for first wash, then gentle hand wash.",
      disclaimer: "Slight thread irregularities are part of hand embroidery."
    },
    image: "/silk.png",
    gallery: ["/wool.png", "/silk.png", "/linen.png", "/coat.jpeg"],
    sizes: ["M", "L", "XL"],
    skuQuantity: 8,
    createdAt: "2025-07-07T12:00:00Z",
    updatedAt: "2025-07-07T12:00:00Z"
  },
  {
    id: 8,
    slug: "mens-black-linen-shirt",
    name: "Men's Black Linen Shirt",
    description: "Comfortable and breathable black linen shirt for smart casual wear.",
    price: 1799,
    discountedPrice: 1499,
    discountPercent: 17,
    category: "shirts",
    color: ["black", "white", "red", "yello"],
    inStock: true,
    rating: 4.5,
    reviewCount: 110,
    productDetails: {
      color: "Black",
      material: "Linen",
      work: ["Plain"],
      materialCare: "Machine wash with mild detergent.",
      disclaimer: "Avoid direct sunlight drying to retain color."
    },
    image: "/linen.png",
    gallery: ["/wool.png", "/silk.png", "/linen.png", "/coat.jpeg"],
    sizes: ["M", "L", "XL", "XXL", "3XL"],
    skuQuantity: 10,
    createdAt: "2025-07-08T09:00:00Z",
    updatedAt: "2025-07-08T09:00:00Z"
  },
  {
    id: 9,
    slug: "mens-grey-formal-trouser",
    name: "Men's Grey Formal Trouser",
    description: "Classic grey formal trousers with a tailored fit and durable fabric.",
    price: 3199,
    discountedPrice: 2799,
    discountPercent: 12,
    category: "trousers",
    color: ["grey"],
    inStock: true,
    rating: 4.6,
    reviewCount: 90,
    productDetails: {
      color: "Grey",
      material: "Cotton Blend",
      work: ["Solid"],
      materialCare: "Machine wash gentle cycle.",
      disclaimer: "Actual color may differ slightly under indoor lighting."
    },
    image: "/coat.jpeg",
    gallery: ["/wool.png", "/silk.png", "/linen.png", "/coat.jpeg"],
    sizes: ["30", "32", "34", "36"],
    skuQuantity: 9,
    createdAt: "2025-07-09T11:00:00Z",
    updatedAt: "2025-07-09T11:00:00Z"
  },
  {
    id: 10,
    slug: "mens-black-three-piece-suit",
    name: "Men's Black Three Piece Suit",
    description: "Classic three-piece black suit featuring premium tailoring and comfort.",
    price: 11999,
    discountedPrice: 9999,
    discountPercent: 17,
    category: "suits",
    color: ["black"],
    inStock: true,
    rating: 4.9,
    reviewCount: 250,
    productDetails: {
      color: "Black",
      material: "Wool Blend",
      work: ["Solid"],
      materialCare: "Dry clean recommended.",
      disclaimer: "The product might appear slightly different under various lighting."
    },
    image: "/coat.jpeg",
    gallery: ["/wool.png", "/silk.png", "/linen.png", "/coat.jpeg"],
    sizes: ["38", "40", "42", "44"],
    skuQuantity: 6,
    createdAt: "2025-07-10T10:00:00Z",
    updatedAt: "2025-07-10T10:00:00Z"
  }
];

